[package]
name = "test_utils"
version = "0.10.0"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2"
solana-sbpf = { path = "../" }
